# Generated by Django 3.0.7 on 2020-06-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedLyrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lyrics', models.TextField()),
                ('seed', models.CharField(max_length=255)),
                ('length', models.IntegerField()),
                ('temperature', models.FloatField()),
            ],
        ),
    ]
